version: "3"
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    restart: always

  app:
    container_name: app
    hostname: app
    image: app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always